# Generated by Django 4.2.28 on 2026-03-08 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_weeklyscore_burnout_index_and_more'),
        ('users', '0003_user_custom_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('spike', 'Spike'), ('threshold', 'Threshold')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('ack', 'Acknowledged'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delta_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('weekly_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.weeklyscore')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
            },
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('weekly_score', 'alert_type'), name='uq_alert_weekly_score_type'),
        ),
    ]
