# Generated by Django 4.2.28 on 2026-03-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("surveys", "0006_remove_surveyanswer_ck_survey_answer_score_1_10_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField()),
                ("stress", models.DecimalField(decimal_places=2, max_digits=4)),
                ("workload", models.DecimalField(decimal_places=2, max_digits=4)),
                ("motivation", models.DecimalField(decimal_places=2, max_digits=4)),
                ("energy", models.DecimalField(decimal_places=2, max_digits=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_score",
                        to="surveys.surveysubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Score",
                "verbose_name_plural": "Weekly Scores",
                "db_table": "weekly_scores",
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyscore",
            constraint=models.CheckConstraint(
                check=models.Q(("week_number__gte", 1), ("week_number__lte", 53)),
                name="ck_weekly_score_week_number_1_53",
            ),
        ),
    ]
