# Generated by Django 4.2.28 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyscore",
            name="burnout_index",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="weeklyscore",
            name="burnout_index_stable",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name="weeklyscore",
            constraint=models.CheckConstraint(
                check=models.Q(("burnout_index__gte", 0), ("burnout_index__lte", 100))
                | models.Q(("burnout_index__isnull", True)),
                name="ck_weekly_score_burnout_index_0_100_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyscore",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("burnout_index_stable__gte", 0), ("burnout_index_stable__lte", 100)
                )
                | models.Q(("burnout_index_stable__isnull", True)),
                name="ck_weekly_score_burnout_index_stable_0_100_or_null",
            ),
        ),
    ]
