# Generated by Django 4.2.28 on 2026-03-04 22:41

from django.db import migrations, models
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_surveysubmission_surveyanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='week_number',
            field=models.PositiveSmallIntegerField(default=surveys.models.get_current_week_number),
        ),
        migrations.AddConstraint(
            model_name='surveysubmission',
            constraint=models.CheckConstraint(check=models.Q(('week_number__gte', 1), ('week_number__lte', 53)), name='ck_survey_submission_week_number_1_53'),
        ),
    ]
