# Generated by Django 4.2.28 on 2026-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_surveysubmission_week_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='surveyanswer',
            name='ck_survey_answer_score_1_10',
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 10)), name='ck_survey_answer_score_0_10'),
        ),
    ]
